### ISSUE TITLE
BTLE failing to start with string error

### ISSUE THREAD

**Issue by hirsts** [FreeAndFair/Qubie#1]
Hardware = RPi3 with DWA-171
I have been testing with Qubie and gone through the install process many times with different combinations and options and cannot not resolve BTLE not working. When Qubie starts it calls the btle service 

qubie.log:
```javascript
[2017-01-27 17:11:20 EST]: started btle service
```
Wifi is running fine and below is "ps -ef" of the failed process:
```javascript
root      1172  1115  0 Jan27 pts/0    00:00:00 [qubie_btle] <defunct>
```
The following error is from qubie.err:
```javascript
 buffer.js:750
        return this.hexWrite(string, offset, length);
                    ^

TypeError: Invalid hex string
    at TypeError (native)
    at Buffer.write (buffer.js:750:21)
    at fromString (buffer.js:203:26)
    at Function.Buffer.from (buffer.js:99:12)
    at new Buffer (buffer.js:80:17)
    at Gap.startAdvertising (/root/Qubie/prototype/node_modules/bleno/lib/hci-socket/gap.js:44:25)
    at BlenoBindings.startAdvertising (/root/Qubie/prototype/node_modules/bleno/lib/hci-socket/bindings.js:31:13)
    at Bleno.startAdvertising (/root/Qubie/prototype/node_modules/bleno/lib/bleno.js:115:20)
    at Bleno.<anonymous> (/root/Qubie/prototype/qubie_btle.js:53:11)
    at emitOne (events.js:96:13)
```

**Comment by dmzimmerman** [comment]
I will take a look when I can; it appears to be an issue with Bleno, but it could also be that Bleno used to correct for some mistake the Qubie code is making and no longer does. Thanks for letting us know!
